language: python
python:
  - "3.7"
  - "3.8"
cache:
  directories:
    - $PIP_CACHE_DIR
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
install:
  - pip install coveralls
  - pip install poetry
  - poetry config virtualenvs.create false && poetry install -n --no-ansi
script:
  - black --check .
  - pytest --cov websocket_notifications
after_success:
  - coveralls