# Generated by Django 4.2.5 on 2023-12-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("websocket_notifications", "0003_auto_20231203_0415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationgroup",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="notificationgroup",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
